global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "integrator"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "localhost:8000" ]

  - job_name: "prometheus"
    honor_labels: true
    static_configs:
      - targets: [ "localhost:9090" ]